### PR TITLE
Done with transaction batching and caching of accounts

### LINKED ISSUE #8: Store proofs per transaction batch or individual transactions
To be able to store txs proofs for high availability, incase of failing to settle

### PR DESCRIPTION
**Pull request by jeevan4476**
fixes #8 

- sequencer no longer processes transactions one by one. Instead, it collects incoming transactions into a "batch" until it reaches a set size 
- With a fully pre-loaded cache, the sequencer hands the entire batch of transactions to the SVM. The SVM can now execute all transactions at high speed because it never has to wait for data; every account it needs is already available in the local cache

yet to be done

1. generating & storing the proofs 
2. if a transaction fails, we can rerun the transaction(just an enhancement [Not really required at this point])

### CODE REVIEW

**Comment by BHEEEET** [comment]
Still the issue of the first batch not being able to settle, like you mentioned, we'll look further into it

File: rollup_client/tests/integration_test.rs [hunk 1]
```diff
@@ -98,8 +98,11 @@ async fn test_complete_rollup_flow() -> Result<()> {
 
     // Create test transaction
     println!("\n2. Creating test transaction...");
-    let sender_keypair = create_test_keypair();
-    let receiver_keypair = create_test_keypair();
+    // let sender_keypair = create_test_keypair();
+    // let receiver_keypair = create_test_keypair();
+    let sender_keypair = signer::keypair::read_keypair_file("/home/jvan/.solana/testkey.json").unwrap();
```
Comment (BHEEEET) [inline rollup_client/tests/integration_test.rs:103]: lets make these paths something universal, where we don't need to keep changing it

File: rollup_client/tests/integration_test.rs [hunk 2]
```diff
@@ -276,8 +282,11 @@ async fn test_rollup_client_functionality() -> Result<()> {
 
     // Test transaction creation utility
     println!("\n2. Testing transaction creation utility...");
-    let keypair1 = create_test_keypair();
-    let keypair2 = create_test_keypair();
+    // let keypair1 = create_test_keypair();
+    // let keypair2 = create_test_keypair();
+    let keypair1 = signer::keypair::read_keypair_file("/home/jvan/.solana/testkey.json").unwrap();
```
Comment (BHEEEET) [inline rollup_client/tests/integration_test.rs:287]: idem

File: rollup_client/tests/integration_test.rs (hunk 1 above)
Comment (SwineCoder101) [reply rollup_client/tests/integration_test.rs:103]: yes thats fair, lets manage keypairs in a .env
